package com.darichey.github.objects

data class Issue(val id: Long,
				 val url: String,
				 val repository_url: String,
				 val labels_url: String,
				 val comments_url: String,
				 val events_url: String,
				 val html_url: String,
				 val number: Int,
				 val state: String,
				 val title: String,
				 val body: String,
				 val user: Sender,
				 val labels: List<Label>,
				 val assignee: Sender,
				 val milestone: Milestone,
				 val locked: Boolean,
				 val comments: Int,
				 val pull_request: PullRequest,
				 val closed_at: String,
				 val created_at: String,
				 val updated_at: String,
				 val closed_by: Sender)